field: 0e945f0d-08ea-4cd7-8fad-5c06abe512df # Content Builder
fieldLayouts:
  d7279194-d52c-45e3-952e-cb12c77b40c9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5836aa34-7573-4d5d-9b2f-0b6304f91187 # Add a Card
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cd90b01-e3ff-43c0-801f-3fb4aa9a0ad1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7c939931-5ab4-4d0e-89a4-149cd6887b86
        userCondition: null
fields:
  5836aa34-7573-4d5d-9b2f-0b6304f91187: # Add a Card
    columnSuffix: ywxszypy
    contentColumnType: string
    fieldGroup: null
    handle: cards
    instructions: null
    name: 'Add a Card'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1405316988
      columns:
        __assoc__:
          -
            - 9ac9d3fa-2774-40a7-a34a-11dc096d303b # Portrait
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - a851aec7-6100-4699-9194-adaed49b220a # Card Name
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 861139bc-6749-4511-a7f1-40c4dc68e2d1 # Body
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 1b163bc5-2ff8-434d-b9e0-d5efe913cbac # Icon
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - f714129d-9105-4558-9586-deeea539208e # Profession
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 4b622811-5251-4ce2-9bb2-d3c1f700cfda # Birthday
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 6d170b95-7f68-4066-8073-d154f9022323 # Social Media
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_2_cards}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: cards
name: Cards
sortOrder: 1
