field: 0e945f0d-08ea-4cd7-8fad-5c06abe512df # Content Builder
fieldLayouts:
  ba46afb0-fe35-4a66-ad49-28178712d36c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f446ef4e-afd6-4a05-8a8f-50350752562e # Images
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b3c4d5a-368b-4293-8c32-6180b9578026
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 074af861-53ed-4150-b43a-2c7ec71e236c
        userCondition: null
fields:
  f446ef4e-afd6-4a05-8a8f-50350752562e: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f82491e5-98a1-400e-8a51-9558e2f03483' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f82491e5-98a1-400e-8a51-9558e2f03483' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: gallery
name: Gallery
sortOrder: 3
