field: 0e945f0d-08ea-4cd7-8fad-5c06abe512df # Content Builder
fieldLayouts:
  d6ef9fee-1d8e-463b-ba05-3cf675c304e6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f7c44e64-367d-4184-b2ca-9835d53c73f9 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5bc4820-188d-4cbd-af5e-3b431527d5ca
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 60685af4-cb8f-4820-ad90-e72dd1b9c473 # Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b1076d8-989c-42d7-9032-00431cfb6a16
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 87ed53b6-0680-4273-aec7-f8b4be63d9d5 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2fda576-8a9c-40eb-9759-16c592779fe7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77430723-778d-42fe-aa44-2f718ae3c502 # Image Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 682ba1be-2933-462f-a45b-b3adb7fb9dbc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a1b0bb33-943a-49b0-8fc1-3d2019a33bf7
        userCondition: null
fields:
  87ed53b6-0680-4273-aec7-f8b4be63d9d5: # Text
    columnSuffix: zihbwyyd
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  60685af4-cb8f-4820-ad90-e72dd1b9c473: # Image Caption
    columnSuffix: efhtwahw
    contentColumnType: text
    fieldGroup: null
    handle: imageCaption
    instructions: null
    name: 'Image Caption'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  77430723-778d-42fe-aa44-2f718ae3c502: # Image Position
    columnSuffix: udbsxhzc
    contentColumnType: string
    fieldGroup: null
    handle: imagePosition
    instructions: null
    name: 'Image Position'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f7c44e64-367d-4184-b2ca-9835d53c73f9: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:f82491e5-98a1-400e-8a51-9558e2f03483' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: false
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f82491e5-98a1-400e-8a51-9558e2f03483' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: imageText
name: Image/Text
sortOrder: 6
