fieldLayouts:
  62ecc526-998d-4475-8db2-5d1b8d03e5bb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 33917feb-bf7d-47bb-81e7-6b24915d0537 # Menu Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cbf730d3-f855-4455-87c1-0b9c3d89a09c
            userCondition: null
            warning: null
            width: 100
        name: 'Main Nav'
        uid: 2300c0e8-223e-4ef8-8c8f-a5e9a55bb73c
        userCondition: null
handle: navMenu
name: 'Nav Menu'
sortOrder: 1
