defaultPlacement: end
enableVersioning: true
handle: invitations
name: Invitations
propagationMethod: all
siteSettings:
  e8ada950-6cd2-4961-9ab8-160d994fb6f7: # Wedding
    enabledByDefault: true
    hasUrls: true
    template: rsvp/_entry
    uriFormat: 'rsvp/{slug}'
type: channel
